### ISSUE TITLE
Rendered Video Contains Only Text Like Terminal

### ISSUE THREAD

**Issue by gotoark** [gotoark/SlideShowMaker#1]
Video Not Created Only Image Paths  Appeared in Video See More Here--> https://stackoverflow.com/questions/46738318/ffmpeg-creates-a-terminal-like-text-video-instead-of-slide-show-of-images

**Comment by deepakrokz** [comment]
You can check by this 
`String command[] = {"-y", "-f", "concat", "-safe", "0", "-i", gpxfile.getAbsolutePath(), "-vsync", "vfr", "-pix_fmt", "yuv420p", root.getAbsolutePath()+"/"+"video.mp4"};`

It will create video file with images

**Comment by gotoark** [comment]
Thanks a Lot, Deepak This Works :1st_place_medal:  💯  @deepakrokz
